# Generated by Django 6.0.4 on 2026-04-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('room_number', models.CharField(max_length=10)),
                ('rent', models.IntegerField()),
                ('joining_date', models.DateField()),
            ],
        ),
    ]
