# Generated by Django 6.0.4 on 2026-04-30 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0002_tenant_created_at_tenant_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='room_number',
        ),
        migrations.AddField(
            model_name='tenant',
            name='bed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pgapp.bed'),
        ),
    ]
