# Generated by Django 6.0.4 on 2026-04-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0003_bed_remove_tenant_room_number_tenant_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='bed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pgapp.bed'),
        ),
    ]
