# Generated by Django 6.0.4 on 2026-04-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0004_alter_tenant_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='id_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_proof_type',
            field=models.CharField(default='AADHAR', max_length=20),
        ),
    ]
