# Generated by Django 6.0.4 on 2026-04-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0005_tenant_id_proof_file_tenant_id_proof_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
