# Generated by Django 6.0.4 on 2026-05-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0009_alter_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='bed',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pgapp.room'),
        ),
    ]
