# Generated by Django 6.0.4 on 2026-05-04 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0010_room_alter_bed_number_bed_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
