# Generated by Django 6.0.4 on 2026-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0011_alter_payment_date_alter_payment_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
